definitions:
  model.UserSignUpInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for test.
  title: Student Swagger API
  version: "2.0"
paths:
  /users/sign-up:
    post:
      consumes:
      - application/json
      description: User registration
      parameters:
      - description: Data for registration user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserSignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Registered
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User registration
      tags:
      - users
swagger: "2.0"
